"""Database models and connection for BTC 5-min trading bot."""
from datetime import datetime
from typing import Optional
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Boolean, JSON, text, event
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy import inspect
import enum

from backend.config import settings

engine = create_engine(
    settings.DATABASE_URL,
    connect_args={"check_same_thread": False} if "sqlite" in settings.DATABASE_URL else {}
)


# Audit HIGH #8 (2026-06-05): WAL mode lets readers (eg the FastAPI /api
# routes serving the dashboard) coexist with the scheduler's writers without
# locking up the DB. busy_timeout=5000 means SQLite will sleep up to 5s on a
# lock contention before raising — eliminates spurious "database is locked"
# errors from short overlap between scan/settlement/dashboard transactions.
# Listener fires on every new dbapi connection (and pool checkouts re-use
# existing connections — listener does not re-run), so this is one-time per
# connection. Safe to leave unconditional; PRAGMA on non-SQLite no-ops are
# avoided because this listener is only attached for SQLite URLs.
if "sqlite" in settings.DATABASE_URL:
    @event.listens_for(engine, "connect")
    def _set_sqlite_pragmas(dbapi_conn, _):
        cur = dbapi_conn.cursor()
        cur.execute("PRAGMA journal_mode=WAL")
        cur.execute("PRAGMA busy_timeout=5000")
        cur.close()


SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


class Trade(Base):
    """Simulated trades for tracking P&L."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, index=True)
    signal_id = Column(Integer, index=True)
    market_ticker = Column(String, index=True)
    platform = Column(String)
    event_slug = Column(String, nullable=True)
    market_type = Column(String, default="btc", index=True)  # "btc" or "weather"

    # Trade details
    direction = Column(String)  # "up" or "down"
    entry_price = Column(Float)
    size = Column(Float)
    timestamp = Column(DateTime, default=datetime.utcnow)

    # Settlement
    settled = Column(Boolean, default=False)
    settlement_time = Column(DateTime, nullable=True)
    settlement_value = Column(Float, nullable=True)  # 1.0=Up won, 0.0=Down won
    result = Column(String, default="pending")  # pending, win, loss
    pnl = Column(Float, nullable=True)

    # Model performance tracking
    model_probability = Column(Float)
    market_price_at_entry = Column(Float)
    edge_at_entry = Column(Float)
    # Realistic-fills hybrid (2026-07-20): how the paper trade was filled —
    # 'instant' (swept at entry) or 'rest_fill' (a resting order later crossed).
    fill_type = Column(String, nullable=True)


class BtcPriceSnapshot(Base):
    """Cached BTC prices for momentum calculation."""
    __tablename__ = "btc_price_snapshots"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    price = Column(Float)
    source = Column(String, default="coingecko")


class BotState(Base):
    """Bot state and statistics."""
    __tablename__ = "bot_state"

    id = Column(Integer, primary_key=True)
    bankroll = Column(Float, default=10000.0)
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    total_pnl = Column(Float, default=0.0)
    last_run = Column(DateTime, nullable=True)
    is_running = Column(Boolean, default=False)


class Signal(Base):
    """Trading signals generated by the bot."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, index=True)
    market_ticker = Column(String, index=True)
    platform = Column(String)
    market_type = Column(String, default="btc", index=True)  # "btc" or "weather"
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)

    direction = Column(String)
    model_probability = Column(Float)
    market_price = Column(Float)
    edge = Column(Float)
    confidence = Column(Float)

    kelly_fraction = Column(Float)
    suggested_size = Column(Float)

    sources = Column(JSON)
    reasoning = Column(String)

    executed = Column(Boolean, default=False)

    # Calibration tracking — filled after settlement
    actual_outcome = Column(String, nullable=True)    # "up" or "down" — actual market result
    outcome_correct = Column(Boolean, nullable=True)   # did our direction prediction match?
    settlement_value = Column(Float, nullable=True)     # 1.0=UP won, 0.0=DOWN won
    settled_at = Column(DateTime, nullable=True)        # when we recorded the outcome

    # Model-upgrade v1 SHADOW (2026-07-01): v2 = per-city/per-model bias-corrected +
    # equal-model-weight GFS/ECMWF pool, logged ALONGSIDE v1. v1 still trades unless
    # WEATHER_MODEL_V2_TRADING. All nullable (NULL when v2 can't be computed — a v2
    # failure must never affect the v1 signal).
    model_probability_v2 = Column(Float, nullable=True)
    ensemble_mean_v2 = Column(Float, nullable=True)
    ensemble_std_v2 = Column(Float, nullable=True)
    bias_applied_json = Column(String, nullable=True)   # {"gfs_seamless": -1.6, "ecmwf_ifs025": 0.0}


class AILog(Base):
    """Log of all AI API calls."""
    __tablename__ = "ai_logs"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    provider = Column(String, index=True)
    model = Column(String)

    prompt = Column(String)
    response = Column(String)
    call_type = Column(String, index=True)

    latency_ms = Column(Float)
    tokens_used = Column(Integer)
    cost_usd = Column(Float)

    related_market = Column(String, nullable=True)
    success = Column(Boolean, default=True)
    error = Column(String, nullable=True)


class ScanLog(Base):
    """Log of each market scan run."""
    __tablename__ = "scan_logs"

    id = Column(Integer, primary_key=True, index=True)
    run_id = Column(String, unique=True, index=True)
    started_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    categories_scanned = Column(JSON)
    platforms_scanned = Column(JSON)

    markets_found = Column(Integer, default=0)
    signals_generated = Column(Integer, default=0)
    trades_executed = Column(Integer, default=0)

    ai_calls_made = Column(Integer, default=0)
    ai_cost_usd = Column(Float, default=0.0)

    success = Column(Boolean, default=True)
    error = Column(String, nullable=True)


class PnlSnapshot(Base):
    """Periodic P&L snapshot, written each heartbeat for dashboard charting."""
    __tablename__ = "pnl_snapshots"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    bankroll = Column(Float, nullable=False)
    exposure = Column(Float, nullable=False)        # sum of size across open weather positions
    realized_pnl = Column(Float, nullable=False)    # cumulative settled P&L
    pending_count = Column(Integer, nullable=False)  # open weather positions
    settled_count = Column(Integer, nullable=False)  # closed weather positions
    is_running = Column(Boolean, default=True)


class ModelBias(Base):
    """Per-(city, model) additive daily-HIGH bias (forecast − ERA5 actual at the
    bot's coords, GMT frame — the model-upgrade groundwork frame). Refreshed
    nightly; bias_f is 0.0 (uncorrected) until n_days >= 20, and clamped ±5°F."""
    __tablename__ = "model_bias"
    id = Column(Integer, primary_key=True)
    city = Column(String, index=True)
    model = Column(String, index=True)
    bias_f = Column(Float, default=0.0)
    n_days = Column(Integer, default=0)
    window_days = Column(Integer, default=30)
    updated_at = Column(DateTime, default=datetime.utcnow)


class ForecastLog(Base):
    """Persist-forward daily-high forecast per (city, model, target_date). The
    ensemble API's past_days is unreliable (sparse members), so the bias window
    is filled by logging each night's forecast and joining to ERA5 actuals as
    they become available. One row per (city, model, target_date) — latest wins."""
    __tablename__ = "forecast_log"
    id = Column(Integer, primary_key=True)
    city = Column(String, index=True)
    model = Column(String, index=True)
    target_date = Column(String, index=True)   # ISO 'YYYY-MM-DD'
    forecast_high = Column(Float)
    recorded_at = Column(DateTime, default=datetime.utcnow)


class PaperRestingOrder(Base):
    """Simulated resting BUY order for the paper realistic-fills hybrid (2026-07-20).
    When an instant sweep leaves an unfilled remainder, we rest it at the entry
    limit price; later scans fill it if the real book's best_ask crosses down to
    <= our rest price (proxy for a seller hitting our bid — conservative, same
    spirit as the live take+rest). Cancelled (rest_expired) at settlement approach."""
    __tablename__ = "paper_resting_orders"
    id = Column(Integer, primary_key=True, index=True)
    signal_id = Column(Integer, nullable=True, index=True)
    market_ticker = Column(String, index=True)
    platform = Column(String, default="polymarket")
    event_slug = Column(String, nullable=True)
    condition_id = Column(String, nullable=True)
    direction = Column(String)                  # "yes" | "no"
    rest_price = Column(Float)                   # entry limit (cap) we rest at
    remaining_shares = Column(Float)             # unfilled shares still resting
    city_name = Column(String, nullable=True)
    target_date = Column(String, index=True)     # ISO 'YYYY-MM-DD' (settlement day)
    model_probability = Column(Float, nullable=True)
    market_price_at_entry = Column(Float, nullable=True)
    edge_at_entry = Column(Float, nullable=True)
    status = Column(String, default="resting", index=True)  # resting|filled|expired
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow)


def init_db():
    """Initialize database tables."""
    Base.metadata.create_all(bind=engine)
    ensure_schema()


def ensure_schema():
    """Ensure newer schema fields exist even if migration wasn't run."""
    inspector = inspect(engine)
    try:
        columns = [col["name"] for col in inspector.get_columns("trades")]
    except Exception:
        return

    if "event_slug" not in columns:
        stmt = "ALTER TABLE trades ADD COLUMN event_slug VARCHAR"
        if engine.dialect.name not in ("sqlite", "mysql"):
            stmt = "ALTER TABLE trades ADD COLUMN IF NOT EXISTS event_slug VARCHAR"

        with engine.connect() as conn:
            with conn.begin():
                conn.execute(text(stmt))

    if "market_type" not in columns:
        with engine.connect() as conn:
            with conn.begin():
                conn.execute(text("ALTER TABLE trades ADD COLUMN market_type VARCHAR DEFAULT 'btc'"))

    if "fill_type" not in columns:   # realistic-fills hybrid (2026-07-20)
        try:
            with engine.connect() as conn:
                with conn.begin():
                    conn.execute(text("ALTER TABLE trades ADD COLUMN fill_type VARCHAR"))
        except Exception:
            pass

    # Add calibration columns to signals table
    try:
        signal_columns = [col["name"] for col in inspector.get_columns("signals")]
    except Exception:
        signal_columns = []

    if signal_columns:
        with engine.connect() as conn:
            for col, coltype in [
                ("actual_outcome", "TEXT"),
                ("outcome_correct", "BOOLEAN"),
                ("settlement_value", "FLOAT"),
                ("settled_at", "DATETIME"),
                ("market_type", "VARCHAR DEFAULT 'btc'"),
                # Model-upgrade v1 shadow columns (2026-07-01, audit model-v1).
                ("model_probability_v2", "FLOAT"),
                ("ensemble_mean_v2", "FLOAT"),
                ("ensemble_std_v2", "FLOAT"),
                ("bias_applied_json", "TEXT"),
            ]:
                if col not in signal_columns:
                    try:
                        with conn.begin():
                            conn.execute(text(f"ALTER TABLE signals ADD COLUMN {col} {coltype}"))
                    except Exception:
                        pass  # column already exists

    # Model-upgrade v1 tables (2026-07-01): create if missing. create_all in
    # init_db already handles new tables, but do it defensively here too so an
    # older DB that skips init_db still gets them (idempotent).
    try:
        Base.metadata.create_all(bind=engine, tables=[ModelBias.__table__, ForecastLog.__table__])
    except Exception:
        pass

    # Realistic-fills resting-order table (2026-07-20): create if missing.
    try:
        Base.metadata.create_all(bind=engine, tables=[PaperRestingOrder.__table__])
    except Exception:
        pass


def get_db():
    """Get database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
